Repository elastic/apm-agent-ios, pull requests merged in 2025-06, with the labels that each got.

#274 Prepare release notes for migration
  .github/CODEOWNERS
  docs/docset.yml
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: documentation, agent-ios, agent-mobile, community, triage

#277 docs-builder: add `pull-requests: write` permission to docs-build workflow
  .github/workflows/docs-build.yml
Labels: agent-ios, agent-mobile

#281 clean up dependencies and supported platform version
  Package.swift
  Sources/apm-agent-ios/ElasticApmAgent.swift
  Sources/apm-agent-ios/Instrumentation/AppMetrics/AppMetrics.swift
  Sources/apm-agent-ios/Instrumentation/CrashReporting/CrashManager.swift
  Sources/apm-agent-ios/Instrumentation/Lifecycle/ApplicationLifecycleInstrumentation.swift
  Sources/apm-agent-ios/Utils/NTPClock.swift
Labels: agent-ios, agent-mobile, community, triage
