Repository elastic/apm-agent-ios, pull requests merged in 2025-07, with the labels that each got.

#284 Add redirects
  docs/docset.yml
  docs/redirects.yml
Labels: agent-ios, agent-mobile, community, triage

#285 ci: move from dependabot reviewers to CODEOWNERS
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: enhancement

#287 github(codeowners): robots-ci can review .github/workflows only
  .github/CODEOWNERS
Labels: agent-ios, agent-mobile
